apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      NodePort: 30080
  selector:
      app: nginx-pod
      type: back-end
