apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
  labels:
    app: meuapp
    type: front-end
spec:
  template:
    metadata: 
      name: meuapp-pod
      labels:
        app: meuapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx

  replicas: 6
  selector:
    matchLabels:
      type: front-end
